#!/usr/bin/env python3

import hanabi
import argparse

def silent(*args, **kwargs):
    pass

parser = argparse.ArgumentParser(
    description='Play a game of Hanabi.')


parser.add_argument("-n", type=int, default=2, help='number of players')
parser.add_argument("--load", "-l", type=str, help='load a replay game')
parser.add_argument("--ai", type=str, help='players are controlled by this AI')
parser.add_argument("-q", "--quiet", action='store_true', help='Quiet mode, only the final score is displayed (requires an ai, obviously)')

args = parser.parse_args()

if args.quiet:
    print = silent

print(args)

print ("\nLet's start a new game")
game = hanabi.Game(args.n)
print ("Here are the hands:")
print (game.hands)

if args.ai:
    game.ai = getattr(hanabi.ai, args.ai)(game)
    print("Playing with this ai:", game.ai.__doc__)

game.quiet = args.quiet

if args.load:
    game.load(args.load)

game.run()
